# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: dimm-city-data-staging

on:
  push:
    branches:
      - release/staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: Set up Node.js version
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16

      # - name: npm install, build, and test
      #   run: |
      #     npm ci
      #     npm run build:prod --if-present
      
      - name: Create Archive of application code
        run: |
          mkdir -p zip
          zip  -r zip/app.zip . -x@.zipignore

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: dimm-city-data
          path: zip/app.zip 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: dimm-city-data

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dimm-city-data-staging'
          slot-name: 'Production'
          publish-profile: ${{ secrets.STAGING_DEPLOY_KEY }}
          package: app.zip
